// <auto-generated />
namespace Game.Persistence.Migrations.Configuration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Set_EmailProperty_In_GameUserEntity_To_Optional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_EmailProperty_In_GameUserEntity_To_Optional));
        
        string IMigrationMetadata.Id
        {
            get { return "201805280234198_Set_EmailProperty_In_GameUserEntity_To_Optional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
