// <auto-generated />
namespace BlackJack.persistence.Migrations.Configuration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class set_aliasLength_to_25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_aliasLength_to_25));
        
        string IMigrationMetadata.Id
        {
            get { return "201804212138565_set_aliasLength_to_25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
