// <auto-generated />
namespace BlackJack.persistence.Migrations.Configuration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changed_GameType_to_GameName_Enum_inTableScoreboard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_GameType_to_GameName_Enum_inTableScoreboard));
        
        string IMigrationMetadata.Id
        {
            get { return "201804220956167_changed_GameType_to_GameName_Enum_inTableScoreboard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
